#! /bin/sh

# Start Simple X Hotkey Daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch Polybar
$XDG_CONFIG_HOME/polybar/launch.sh

# Restore Wallpapers
nitrogen --restore

# Run dex for autostart applications.
dex -a

# Bspwm Configuration
bspc monitor DP-2 -d     

bspc config border_width            2
bspc config window_gap              5
bspc config -m DP-2 top_padding     20

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
